services:
  flash-go:
    build:
      context: .
    container_name: flash-go-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      APK_DOWNLOAD_URL: ${APK_DOWNLOAD_URL:-https://drive.google.com/uc?export=download&id=ID_DEL_ARCHIVO}
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
